replicaCount: 1

image:
  repository: sonatype/nexus3
  tag: "3.78.2"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podLabels: {}
podAnnotations: {}

securityContext: {}

javaOptions:
  maxHeap: "800m"
  minHeap: "300m"

extraEnv: []

service:
  type: ClusterIP
  port: 8085
  webdavPort: 8086
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /service/metrics/prometheus
    prometheus.io/port: '8085'

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

resources:
  limits:
    memory: "4Gi"
    cpu: "1000m"
  requests:
    memory: "2Gi"
    cpu: "500m"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClassName: "" 
  annotations: {}


