apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /service/metrics/prometheus
      prometheus.io/port:   '8081'
spec:
  selector: 
    app: nexus-server
  type: ClusterIP
  ports:
    - name: docker
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: admin
      protocol: TCP
      port: 8082
      targetPort: 8082