apiVersion: v1
kind: Service
metadata:
  name: {{ include "j.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: {{ .Values.selector.app }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
      {{- if .Values.service.ports.nodePort }}
      nodePort: {{ .Values.service.ports.nodePort }}
      {{- end }}