
replicaCount: 1

image:
  repository: alberguarchu/jenkinskom
  pullPolicy: Always
  tag: latest

serviceAccountName: jenkins-admin

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

resources:
  limits:
    memory: 2Gi
    cpu: 1000m
  requests:
    memory: 500Mi
    cpu: 500m


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}


securityContext: {}

selector:
  app: jenkins-server
service:
  type: NodePort
  ports:
    port: 8080
    targetPort: 8080
    nodePort: 31002
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /prometheus/
    prometheus.io/port: '8080'

storage:
  storageClassName: "local-storage"

persistentVolume:
  labels: {}
  capacity: "10Gi"
  local:
    path: "/mnt"
  nodeAffinity:
    hostname: "minikube"

persistentVolumeClaim:
  annotations: {}
  size: "3Gi"
  selector: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
