apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: {{ include "nexus.name" . }}-server
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port | default 8081 }}
      targetPort: {{ .Values.service.port | default 8081 }}
    - name: webdav
      protocol: TCP
      port: {{ .Values.service.webdavPort | default 8082 }}
      targetPort: {{ .Values.service.webdavPort | default 8082 }}
