global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: elzim # Change to whatever you like
    static_configs:
      - targets: 
        - node-exporter:9100
  - job_name: jenkins
    metrics_path: '/prometheus/'
    static_configs:
      - targets:
        - jenkins:8080
    basic_auth:
      username: 'admin'
      password: '116501bc2ac3f909ad2145972e267003e0'
      #11c71a809c1786d93ddfd52e1db6598cf1
  - job_name: nexus
    metrics_path: '/service/metrics/prometheus'
    basic_auth:    
      username: Prometheus   
      password: password
    static_configs:
      - targets:
        - nexus:8081

