apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: tfm-container
        image: alberguarchu/tfmweb:latest
        ports:
        - containerPort: 3000 
---
apiVersion: v1
kind: Service
metadata:
  name: webs
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 3000 
    targetPort: 3000
  type: NodePort
