version: '3.8'

services:
  web:
    image: alberguarchu/tfmweb:latest
    ports:
      - "30000:80"
    depends_on:
      - repodown
    networks:
      - devops-net

  repodown:
    image: alberguarchu/repogit:latest
    ports:
      - "30001:8000"
    networks:
      - devops-net

  jenkins:
    image: jenkins/jenkins:lts
    user: "1000:1000"
    ports:
      - "32000:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Xmx2g
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - devops-net

  nexus:
    image: sonatype/nexus:latest
    environment:
      - MAX_HEAP=800m
      - MIN_HEAP=300m
    ports:
      - "32001:8081"
    volumes:
      - nexus-data:/sonatype-work
    networks:
      - devops-net

volumes:
  jenkins-data:
  nexus-data:
    driver: local

networks:
  devops-net:
    driver: bridge
