services:
  web:
    image: alberguarchu/tfmweb:latest
    ports:
      - "30000:80"
    depends_on:
      - repodown
    networks:
      - devops-net

  repodown:
    image: alberguarchu/repogit:latest
    ports:
      - "30001:8000"
    networks:
      - devops-net

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    privileged: true
    ports:
      - "30002:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Xmx2g
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops-net

  nexus:
    image: sonatype/nexus:latest
    environment:
      - MAX_HEAP=800m
      - MIN_HEAP=300m
    ports:
      - "30003:8081"
    volumes:
      - nexus-data:/sonatype-work
    networks:
      - devops-net
      
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '30004:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - devops-net
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 30005:9090
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
    networks:
      - devops-net
  node-exporter:
    image: prom/node-exporter
    ports:
      - 30006:9100
    networks:
      - devops-net
  keycloack:
    image: quay.io/keycloak/keycloak:26.1.2
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080"]
    ports:
      - "30007:7080"
    networks:
      - devops-net

volumes:
  jenkins-data:
  nexus-data:
    driver: local
  grafana-storage: {}
  prom_data:

networks:
  devops-net:
    driver: bridge
