apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus3-pv
spec:
  capacity:
    storage: 10Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/nexus3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus3-pvc
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: tools
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: nexus
        image: sonatype/nexus3:latest 
        ports:
          - containerPort: 8081
          - containerPort: 8082
        volumeMounts:
          - name: nexus3-storage
            mountPath: /nexus-data 
      volumes:
        - name: nexus3-storage
          persistentVolumeClaim:
            claimName: nexus3-pvc 
---
apiVersion: v1
kind: Service
metadata:
  name: nexus3
  namespace: tools
spec:
  selector:
    app: nexus
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: docker
      port: 8082
      targetPort: 8082
      nodePort: 32003
  type: LoadBalancer
