apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-admin-prueba
  namespace: prueba
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apps", "batch", "extensions"]
    resources: ["*"] 
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"] 
    resources: ["roles", "rolebindings"] 
    verbs: ["*"] 

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-admin-prueba-binding
  namespace: prueba 
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: prueba
roleRef:
  kind: Role
  name: jenkins-admin-prueba
  apiGroup: rbac.authorization.k8s.io 