apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dep
  labels:
    env: sandbox
spec:
  replicas: 3
  selector:
    matchLabels:
      env: sandbox
  template:
    metadata:
      labels:
        env: sandbox
    spec:
      containers:
      - name: web
        image: alberguarchu/tfmweb:latest
        ports:
        - containerPort: 80